import { startAlfred } from '/home/quinna/repos/alfred-wt/P5/src/main.js';
import { chromium } from 'playwright-core';
import { mkdtempSync } from 'node:fs';
import { tmpdir, homedir } from 'node:os';
import { join } from 'node:path';
const EXE = join(homedir(), '.cache/ms-playwright/chromium_headless_shell-1228/chrome-linux/headless_shell');
const base = mkdtempSync(join(tmpdir(), 'dbg-'));
const alfred = await startAlfred({ dbPath: join(base,'a.db'), mirrorDir: join(base,'v'), workRoot: join(base,'w'), personasDir:'personas', port:0, host:'127.0.0.1', pollMs:25, deck:null, env:{ALFRED_NOTIFY_DESKTOP:'0'}, llm:{ async chat(){ await new Promise(r=>setTimeout(r,60000)); return {content:'',toolCalls:[],usage:{promptTokens:1,completionTokens:1}}; } } });
console.log('URL', alfred.url);
const r = await fetch(alfred.url + '/'); console.log('GET / ->', r.status, (await r.text()).slice(0,120));
const g = await fetch(alfred.url + '/api/goals', { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({title:'DBG goal', persona:'coder', spec:'s', acceptance:[{name:'a',cmd:'true'}]}) }).then(r=>r.json());
console.log('created', JSON.stringify(g).slice(0,200));
const b = await chromium.launch({ executablePath: EXE });
const p = await b.newPage();
p.on('console', m => console.log('PAGE', m.type(), m.text().slice(0,200)));
p.on('pageerror', e => console.log('PAGEERR', (e.stack||String(e)).slice(0,800)));
p.on('requestfailed', rq => console.log('REQFAIL', rq.url().slice(0,120), rq.failure()?.errorText));
await p.goto(alfred.url + '/#/');
await p.waitForTimeout(2500);
console.log('BODY:', (await p.evaluate(() => document.body.innerText)).slice(0, 600));
await p.goto(`${alfred.url}/#/goal/${g.goal.id}`);
await p.waitForTimeout(1500);
console.log('DETAIL:', (await p.evaluate(() => document.body.innerText)).slice(0, 600));
await p.goto(`${alfred.url}/#/personas`);
await p.waitForTimeout(1500);
console.log('PERSONAS:', (await p.evaluate(() => document.body.innerText)).slice(0, 400));
await b.close(); await alfred.stop();
